sudo: false
language: node_js
node_js:
  - 0.12
after_success: npm run report-coverage
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    # d2l-travis-deploy: 8eae......65cd
    secure: puTmjlbCLrH5AOylb5vFb3CBtGyGZ40Lu6f2rcrfo+aKktMn3Zft7jjbmbrEVMecJS50Z0pb6tcoaBqjzSMVw9ypJAu5Xj8NcUkJy/YsT/sf0JXM+Vv6RhtwgdEk/4e1HxWpidoz07n8kUa5qO04WcTA9mPbqbB4/RKqdz8myiU=
  on:
    tags: true
    repo: Brightspace/superagent-d2l-session-auth
    all_branches: true
