sudo: false
language: node_js
node_js:
- 0.12
after_success: npm run report-coverage
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: bwwFaIOnbDjxf9zjKDsM6SDdtBCN/anCDqS3EXtTBe+l5uRvFW6HwOa3gQV5ZjH9yqhOtO+8X6l1QiCa0+1grLRON/MjTs9drB3mDuNLMNr2ravGBz1aYszQCAnNF1/MNxUjHmK/OBDI34tCpkhvErX/EyGP0hP+Ua25czMuKEc=
  on:
    tags: true
    repo: Brightspace/superagent-d2l-session-auth
    all_branches: true
